@startuml

class IUsuario <<interface>> {
    + eDevedor(): boolean
    + chegouLimiteEmprestimos(): boolean
    + estouComEsteLivroEmprestado(livro: Livro): boolean
    + pegarLivroEmprestado(usuario: Usuario, livro: Livro): RetornoComando
}

@enduml