@startuml

class LivroObservado {
    - notificacoes: Integer
    - livro: Livro

    + LivroObservado(livro: Livro)
    + incrementarNotificacao(): void
    + getNotificacoes(): Integer
    + getLivro(): Livro
}

@enduml