@startuml

class Entrada  {
    - comandoString: String
    - parametros: List<String>

    + processarComando(comando: String): void
    + primeiroParametroInValido(): boolean
    + parametrosInValidos(): boolean
    + getComandoString(): String
    + getParametro0(): String
    + getParametro1(): String
}

@enduml