@startuml

class Biblioteca <<(S,#ff00aa) singleton>> {
    - instance: Biblioteca
    - ultimoLivroReservado: Livro
    - usuarios: HashSet<Usuario>
    - livros: HashSet<Livro>

    - Biblioteca()
    +getInstance(): Biblioteca
    +addUsuario(usuario: Usuario): void
    +addLivro(livro: Livro): void
    +addExemplar(exemplar: Exemplar): void
    +temEsteLivro(livro: Livro): boolean
    +encontrarUsuarioPorCodigo(codigo: String): Usuario
    +encontrarLivroPorCodigo(codigo: String): Livro
    +emprestarLivro(usuario: Usuario, livro: Livro): RetornoComando
    +devolverLivro(usuario: Usuario, livro: Livro): RetornoComando
    +reservarLivro(usuario: Usuario, livro: Livro): RetornoComando
    +observarLivro(usuario: Usuario, livro: Livro): RetornoComando
    +consultarLivro(livro: Livro): RetornoComando
    +consultarUsuario(usuario: Usuario): RetornoComando
    +consultarNotificacao(usuario: Usuario): RetornoComando
    +sair(): RetornoComando
}

@enduml