@startuml

class Emprestimo {
    +devolverExemplarLivro(exemplar: Exemplar): void
        +emprestadoPara(): String
        +toStrinDataEmprestimo(): String
        +toStrinDataDevolucao(): String
}

@enduml