@startuml

class Exemplar {
    -String codigo
    -Livro livro
    -Emprestimo emprestimo
    +Exemplar(codigo: String, livro: Livro)
    +mesmoLivro(livro: Livro): boolean
    +toStringParaLivro(): String
    +devolverExemplarLivro(emprestimoDevolucao: Emprestimo): void
    +getTituloLivro(): String
    +getCodigo(): String
    +getLivro(): Livro
    +isDisponivel(): boolean
    +getEmprestimo(): Emprestimo
    +setEmprestimo(emprestimo: Emprestimo): void
}

@enduml