@startuml

class FabricaGeral {
    +criarLivro(codigo: String, titulo: String, editora: String, edicao: int, ano: int, autores: HashSet<String>): Livro
    +criarExemplar(codigo: String, livro: Livro): Exemplar
}

@enduml