@startuml

class Servidor <<(S,#ff00aa) singleton>> {
    - instance: Servidor
    - comandos: HashMap<String, IComando>

    + getInstance(): Servidor
    + invocarComando(entrada: Entrada): RetornoComando
    - Servidor(): void
    - iniciarComandos();
}

@enduml