@startuml

class ConsultarUsuario {
    + atributoPublico: Integer
    - atributoPrivado: String
    # atributoProtegido: NomeOutraClasse

    + funcaoPublica(Usuario, Livro): void
    - funcaoPrivada(Integer, String): boolean
    # funcaoProtegida(ArrayList<Integer>): Integer
}

@enduml