@startuml
!include src puml/00 - entrada - COMMAND.puml
@enduml

@startuml
!include src puml/01 - comandos - COMMAND.puml
@enduml

@startuml
!include src puml/02 - usuario-observer - OBSERVER-STRATEGY.puml
@enduml

@startuml
!include src puml/03 - processamento - SINGLETON.puml
@enduml

@startuml
!include src puml/04 - estado - STATE.puml
@enduml
